### ISSUE TITLE
Sync with upstream repository, pyprojroot

### ISSUE THREAD

**Issue by chendaniely** [wildland-creative/pyhere#9]
Hello 👋 @joshpsawyer we've made a bunch of internal changes to pyprojroot. Wondering if you are potentially sync up with the repository?
My main thinking was we would make `pyhere.here()` as a thin wrapper around `pyprojroot.here.here()`? would reduce potential maintenance things on your end, and we can work on how both packages can share a common `root_indicator` values.

Mainly asking because I think it would be nice to have both of these packages be submitted as a pair for pyopensci and potentially a JOSS publication.

Related "upstream" issues: https://github.com/chendaniely/pyprojroot/issues/40 https://github.com/chendaniely/pyprojroot/issues/18 https://github.com/chendaniely/pyprojroot/issues/14

**Comment by joshpsawyer** [comment]
Hi @chendaniely ! Fine in theory, but my big concern is that you have no backwards compatibility with Python 2.X - I use `pyhere` with a lot of legacy code. Yes, 2.X has been officially sunsetted but I've encountered a lot of people in academia still writing in 2.X because they don't have time to refactor to 3.X and it's what they know. For that reason, it can't be a wrapper because it'll break legacy projects (at least my own 😎).

Please correct me if I'm mistaken, though!
